server:
  port: 8080
logging:
  level: info
database:
  master:
    driver: postgres
    host: localhost
    port: 5432
    username: prod_user
    password: prod_password
    name: prod_db
    sslmode: disable
bcrypt:
  cost: 10
jwt:
  secret: verysecretkey
  expiration_hours: 72
timezone:
  location: Asia/Jakarta
