// Code generated by ent, DO NOT EDIT.

package authsession

import (
	"skeleton/infra/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldUpdateTime, v))
}

// RefreshTokenID applies equality check predicate on the "refresh_token_id" field. It's identical to RefreshTokenIDEQ.
func RefreshTokenID(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldRefreshTokenID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldUserID, v))
}

// RefreshToken applies equality check predicate on the "refresh_token" field. It's identical to RefreshTokenEQ.
func RefreshToken(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldRefreshToken, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldUserAgent, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldExpiresAt, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLTE(FieldUpdateTime, v))
}

// RefreshTokenIDEQ applies the EQ predicate on the "refresh_token_id" field.
func RefreshTokenIDEQ(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldRefreshTokenID, v))
}

// RefreshTokenIDNEQ applies the NEQ predicate on the "refresh_token_id" field.
func RefreshTokenIDNEQ(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNEQ(FieldRefreshTokenID, v))
}

// RefreshTokenIDIn applies the In predicate on the "refresh_token_id" field.
func RefreshTokenIDIn(vs ...string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldIn(FieldRefreshTokenID, vs...))
}

// RefreshTokenIDNotIn applies the NotIn predicate on the "refresh_token_id" field.
func RefreshTokenIDNotIn(vs ...string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNotIn(FieldRefreshTokenID, vs...))
}

// RefreshTokenIDGT applies the GT predicate on the "refresh_token_id" field.
func RefreshTokenIDGT(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGT(FieldRefreshTokenID, v))
}

// RefreshTokenIDGTE applies the GTE predicate on the "refresh_token_id" field.
func RefreshTokenIDGTE(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGTE(FieldRefreshTokenID, v))
}

// RefreshTokenIDLT applies the LT predicate on the "refresh_token_id" field.
func RefreshTokenIDLT(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLT(FieldRefreshTokenID, v))
}

// RefreshTokenIDLTE applies the LTE predicate on the "refresh_token_id" field.
func RefreshTokenIDLTE(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLTE(FieldRefreshTokenID, v))
}

// RefreshTokenIDContains applies the Contains predicate on the "refresh_token_id" field.
func RefreshTokenIDContains(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldContains(FieldRefreshTokenID, v))
}

// RefreshTokenIDHasPrefix applies the HasPrefix predicate on the "refresh_token_id" field.
func RefreshTokenIDHasPrefix(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldHasPrefix(FieldRefreshTokenID, v))
}

// RefreshTokenIDHasSuffix applies the HasSuffix predicate on the "refresh_token_id" field.
func RefreshTokenIDHasSuffix(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldHasSuffix(FieldRefreshTokenID, v))
}

// RefreshTokenIDEqualFold applies the EqualFold predicate on the "refresh_token_id" field.
func RefreshTokenIDEqualFold(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEqualFold(FieldRefreshTokenID, v))
}

// RefreshTokenIDContainsFold applies the ContainsFold predicate on the "refresh_token_id" field.
func RefreshTokenIDContainsFold(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldContainsFold(FieldRefreshTokenID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLTE(FieldUserID, v))
}

// RefreshTokenEQ applies the EQ predicate on the "refresh_token" field.
func RefreshTokenEQ(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldRefreshToken, v))
}

// RefreshTokenNEQ applies the NEQ predicate on the "refresh_token" field.
func RefreshTokenNEQ(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNEQ(FieldRefreshToken, v))
}

// RefreshTokenIn applies the In predicate on the "refresh_token" field.
func RefreshTokenIn(vs ...string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldIn(FieldRefreshToken, vs...))
}

// RefreshTokenNotIn applies the NotIn predicate on the "refresh_token" field.
func RefreshTokenNotIn(vs ...string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNotIn(FieldRefreshToken, vs...))
}

// RefreshTokenGT applies the GT predicate on the "refresh_token" field.
func RefreshTokenGT(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGT(FieldRefreshToken, v))
}

// RefreshTokenGTE applies the GTE predicate on the "refresh_token" field.
func RefreshTokenGTE(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGTE(FieldRefreshToken, v))
}

// RefreshTokenLT applies the LT predicate on the "refresh_token" field.
func RefreshTokenLT(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLT(FieldRefreshToken, v))
}

// RefreshTokenLTE applies the LTE predicate on the "refresh_token" field.
func RefreshTokenLTE(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLTE(FieldRefreshToken, v))
}

// RefreshTokenContains applies the Contains predicate on the "refresh_token" field.
func RefreshTokenContains(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldContains(FieldRefreshToken, v))
}

// RefreshTokenHasPrefix applies the HasPrefix predicate on the "refresh_token" field.
func RefreshTokenHasPrefix(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldHasPrefix(FieldRefreshToken, v))
}

// RefreshTokenHasSuffix applies the HasSuffix predicate on the "refresh_token" field.
func RefreshTokenHasSuffix(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldHasSuffix(FieldRefreshToken, v))
}

// RefreshTokenEqualFold applies the EqualFold predicate on the "refresh_token" field.
func RefreshTokenEqualFold(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEqualFold(FieldRefreshToken, v))
}

// RefreshTokenContainsFold applies the ContainsFold predicate on the "refresh_token" field.
func RefreshTokenContainsFold(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldContainsFold(FieldRefreshToken, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldContainsFold(FieldUserAgent, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLTE(FieldExpiresAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuthSession) predicate.AuthSession {
	return predicate.AuthSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuthSession) predicate.AuthSession {
	return predicate.AuthSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuthSession) predicate.AuthSession {
	return predicate.AuthSession(sql.NotPredicates(p))
}
