// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in skeleton/infra/ent/runtime.go

const (
	Version = "v0.14.6-0.20260108211107-2eb36418a02e"           // Version of ent codegen.
	Sum     = "h1:7KEvbOmUkRoLWiDBq+CL46PM1C7SOw4XnGYmkRW8fYs=" // Sum of ent codegen.
)
