// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"skeleton/infra/ent/authsession"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthSessionCreate is the builder for creating a AuthSession entity.
type AuthSessionCreate struct {
	config
	mutation *AuthSessionMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *AuthSessionCreate) SetCreateTime(v time.Time) *AuthSessionCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *AuthSessionCreate) SetNillableCreateTime(v *time.Time) *AuthSessionCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *AuthSessionCreate) SetUpdateTime(v time.Time) *AuthSessionCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *AuthSessionCreate) SetNillableUpdateTime(v *time.Time) *AuthSessionCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetRefreshTokenID sets the "refresh_token_id" field.
func (_c *AuthSessionCreate) SetRefreshTokenID(v string) *AuthSessionCreate {
	_c.mutation.SetRefreshTokenID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AuthSessionCreate) SetUserID(v int) *AuthSessionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRefreshToken sets the "refresh_token" field.
func (_c *AuthSessionCreate) SetRefreshToken(v string) *AuthSessionCreate {
	_c.mutation.SetRefreshToken(v)
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *AuthSessionCreate) SetUserAgent(v string) *AuthSessionCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AuthSessionCreate) SetExpiresAt(v time.Time) *AuthSessionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// Mutation returns the AuthSessionMutation object of the builder.
func (_c *AuthSessionCreate) Mutation() *AuthSessionMutation {
	return _c.mutation
}

// Save creates the AuthSession in the database.
func (_c *AuthSessionCreate) Save(ctx context.Context) (*AuthSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthSessionCreate) SaveX(ctx context.Context) *AuthSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthSessionCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := authsession.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := authsession.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthSessionCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "AuthSession.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "AuthSession.update_time"`)}
	}
	if _, ok := _c.mutation.RefreshTokenID(); !ok {
		return &ValidationError{Name: "refresh_token_id", err: errors.New(`ent: missing required field "AuthSession.refresh_token_id"`)}
	}
	if v, ok := _c.mutation.RefreshTokenID(); ok {
		if err := authsession.RefreshTokenIDValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token_id", err: fmt.Errorf(`ent: validator failed for field "AuthSession.refresh_token_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AuthSession.user_id"`)}
	}
	if _, ok := _c.mutation.RefreshToken(); !ok {
		return &ValidationError{Name: "refresh_token", err: errors.New(`ent: missing required field "AuthSession.refresh_token"`)}
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		return &ValidationError{Name: "user_agent", err: errors.New(`ent: missing required field "AuthSession.user_agent"`)}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := authsession.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "AuthSession.user_agent": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AuthSession.expires_at"`)}
	}
	return nil
}

func (_c *AuthSessionCreate) sqlSave(ctx context.Context) (*AuthSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthSessionCreate) createSpec() (*AuthSession, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authsession.Table, sqlgraph.NewFieldSpec(authsession.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(authsession.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(authsession.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.RefreshTokenID(); ok {
		_spec.SetField(authsession.FieldRefreshTokenID, field.TypeString, value)
		_node.RefreshTokenID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(authsession.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.RefreshToken(); ok {
		_spec.SetField(authsession.FieldRefreshToken, field.TypeString, value)
		_node.RefreshToken = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(authsession.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(authsession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// AuthSessionCreateBulk is the builder for creating many AuthSession entities in bulk.
type AuthSessionCreateBulk struct {
	config
	err      error
	builders []*AuthSessionCreate
}

// Save creates the AuthSession entities in the database.
func (_c *AuthSessionCreateBulk) Save(ctx context.Context) ([]*AuthSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthSessionCreateBulk) SaveX(ctx context.Context) []*AuthSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
