// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"skeleton/infra/ent/authsession"
	"skeleton/infra/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthSessionUpdate is the builder for updating AuthSession entities.
type AuthSessionUpdate struct {
	config
	hooks    []Hook
	mutation *AuthSessionMutation
}

// Where appends a list predicates to the AuthSessionUpdate builder.
func (_u *AuthSessionUpdate) Where(ps ...predicate.AuthSession) *AuthSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *AuthSessionUpdate) SetUpdateTime(v time.Time) *AuthSessionUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuthSessionUpdate) SetUserID(v int) *AuthSessionUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableUserID(v *int) *AuthSessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AuthSessionUpdate) AddUserID(v int) *AuthSessionUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *AuthSessionUpdate) SetRefreshToken(v string) *AuthSessionUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableRefreshToken(v *string) *AuthSessionUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *AuthSessionUpdate) SetUserAgent(v string) *AuthSessionUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableUserAgent(v *string) *AuthSessionUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// Mutation returns the AuthSessionMutation object of the builder.
func (_u *AuthSessionUpdate) Mutation() *AuthSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := authsession.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthSessionUpdate) check() error {
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := authsession.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "AuthSession.user_agent": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authsession.Table, authsession.Columns, sqlgraph.NewFieldSpec(authsession.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(authsession.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(authsession.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(authsession.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(authsession.FieldRefreshToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(authsession.FieldUserAgent, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthSessionUpdateOne is the builder for updating a single AuthSession entity.
type AuthSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthSessionMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *AuthSessionUpdateOne) SetUpdateTime(v time.Time) *AuthSessionUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuthSessionUpdateOne) SetUserID(v int) *AuthSessionUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableUserID(v *int) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AuthSessionUpdateOne) AddUserID(v int) *AuthSessionUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *AuthSessionUpdateOne) SetRefreshToken(v string) *AuthSessionUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableRefreshToken(v *string) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *AuthSessionUpdateOne) SetUserAgent(v string) *AuthSessionUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableUserAgent(v *string) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// Mutation returns the AuthSessionMutation object of the builder.
func (_u *AuthSessionUpdateOne) Mutation() *AuthSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthSessionUpdate builder.
func (_u *AuthSessionUpdateOne) Where(ps ...predicate.AuthSession) *AuthSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthSessionUpdateOne) Select(field string, fields ...string) *AuthSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthSession entity.
func (_u *AuthSessionUpdateOne) Save(ctx context.Context) (*AuthSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthSessionUpdateOne) SaveX(ctx context.Context) *AuthSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := authsession.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthSessionUpdateOne) check() error {
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := authsession.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "AuthSession.user_agent": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthSessionUpdateOne) sqlSave(ctx context.Context) (_node *AuthSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authsession.Table, authsession.Columns, sqlgraph.NewFieldSpec(authsession.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authsession.FieldID)
		for _, f := range fields {
			if !authsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(authsession.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(authsession.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(authsession.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(authsession.FieldRefreshToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(authsession.FieldUserAgent, field.TypeString, value)
	}
	_node = &AuthSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
