// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"skeleton/internal/api/etc/delivery"
)

// Injectors from delivery_wire.go:

func InitDeliveryDeps() *DeliveryDependency {
	etcHandler := etcdelivery.NewEtcHandler()
	deliveryDependency := NewDeliveryDependency(etcHandler)
	return deliveryDependency
}

// delivery_wire.go:

type DeliveryDependency struct {
	EtcHandler *etcdelivery.EtcHandler
}

func NewDeliveryDependency(
	etcHandler *etcdelivery.EtcHandler,
) *DeliveryDependency {
	return &DeliveryDependency{
		EtcHandler: etcHandler,
	}
}
