// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"skeleton/infra/ent"
	authdelivery "skeleton/internal/api/auth/delivery"
	authusecase "skeleton/internal/api/auth/usecase"
	errordelivery "skeleton/internal/api/error/delivery"
	etcdelivery "skeleton/internal/api/etc/delivery"
	userrepository "skeleton/internal/api/user/repository"
	"skeleton/pkg/logger"
	"skeleton/pkg/security"
)

// Injectors from wire.go:

func NewContainer(logger2 *logger.Logger, db *ent.Client, sec *security.Security) *Container {
	etcHandler := etcdelivery.NewEtcHandler()
	errorHandler := errordelivery.NewErrorHandler()
	userRepository := userrepository.NewUserRepository(logger2)
	authUsecase := authusecase.NewAuthUsecase(logger2, sec, db, userRepository)
	authHandler := authdelivery.NewAuthHandler(authUsecase)
	container := &Container{
		EtcHandler:   etcHandler,
		ErrorHandler: errorHandler,
		AuthHandler:  authHandler,
	}
	return container
}

// wire.go:

type Container struct {
	EtcHandler   *etcdelivery.EtcHandler
	ErrorHandler *errordelivery.ErrorHandler
	AuthHandler  *authdelivery.AuthHandler
}
