// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"skeleton/internal/api/error/delivery"
	"skeleton/internal/api/etc/delivery"
)

// Injectors from delivery_wire.go:

func NewDeliveryContainer() *DeliveryContainer {
	errorHandler := errordelivery.NewErrorHandler()
	etcHandler := etcdelivery.NewEtcHandler()
	deliveryContainer := &DeliveryContainer{
		ErrorHandler: errorHandler,
		EtcHandler:   etcHandler,
	}
	return deliveryContainer
}

// delivery_wire.go:

type DeliveryContainer struct {
	ErrorHandler *errordelivery.ErrorHandler
	EtcHandler   *etcdelivery.EtcHandler
}
