-- Create "auth_sessions" table
CREATE TABLE "public"."auth_sessions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "user_id" bigint NOT NULL,
  "refresh_token" character varying NOT NULL,
  "user_agent" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "auth_sessions_refresh_token_key" to table: "auth_sessions"
CREATE UNIQUE INDEX "auth_sessions_refresh_token_key" ON "public"."auth_sessions" ("refresh_token");
-- Create index "authsession_user_id_refresh_token" to table: "auth_sessions"
CREATE INDEX "authsession_user_id_refresh_token" ON "public"."auth_sessions" ("user_id", "refresh_token");
