-- Create "users" table
CREATE TABLE "public"."users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "first_name" character varying NOT NULL,
  "last_name" character varying NOT NULL,
  "email" character varying NOT NULL,
  "password" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "user_email" to table: "users"
CREATE INDEX "user_email" ON "public"."users" ("email");
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "public"."users" ("email");
