-- Create "auth_sessions" table
CREATE TABLE "public"."auth_sessions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "refresh_token_id" character varying NOT NULL,
  "user_id" bigint NOT NULL,
  "refresh_token" character varying NOT NULL,
  "user_agent" character varying NOT NULL,
  "expires_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "auth_sessions_refresh_token_id_key" to table: "auth_sessions"
CREATE UNIQUE INDEX "auth_sessions_refresh_token_id_key" ON "public"."auth_sessions" ("refresh_token_id");
-- Create index "auth_sessions_refresh_token_key" to table: "auth_sessions"
CREATE UNIQUE INDEX "auth_sessions_refresh_token_key" ON "public"."auth_sessions" ("refresh_token");
-- Create index "authsession_refresh_token_id" to table: "auth_sessions"
CREATE INDEX "authsession_refresh_token_id" ON "public"."auth_sessions" ("refresh_token_id");
