// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/user": {
            "get": {
                "description": "Endpoint to list example items",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API / User"
                ],
                "summary": "List User Endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/skeleton_pkg_data_dto.SuccessHTTPResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/skeleton_pkg_data_dto.ErrorHTTPResponse"
                        }
                    }
                }
            }
        },
        "/public/health": {
            "get": {
                "description": "Endpoint to check the health of the service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public API / Etc"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/skeleton_pkg_data_dto.SuccessHTTPResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/skeleton_pkg_data_dto.ErrorHTTPResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "skeleton_pkg_data_dto.ErrorDto": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "skeleton_pkg_data_dto.ErrorHTTPResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/skeleton_pkg_data_dto.ErrorDto"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "skeleton_pkg_data_dto.MetaDto": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "size_per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "skeleton_pkg_data_dto.SuccessHTTPResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {
                    "$ref": "#/definitions/skeleton_pkg_data_dto.MetaDto"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Skeleton API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
