// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "Endpoint to login user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API / Auth"
                ],
                "summary": "Login Endpoint",
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/skeleton_internal_api_auth_data_dto.PostAuthLoginRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/skeleton_pkg_data_dto.HTTPResponse-skeleton_internal_api_auth_data_dto_PostAuthLoginResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/skeleton_pkg_data_dto.ErrorHTTPResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/skeleton_pkg_data_dto.ErrorHTTPResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/skeleton_pkg_data_dto.ValidationErrorHTTPResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/skeleton_pkg_data_dto.ErrorHTTPResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/token/refresh": {
            "post": {
                "description": "Endpoint to refresh access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API / Auth"
                ],
                "summary": "Refresh Access Token Endpoint",
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/skeleton_internal_api_auth_data_dto.PostAuthTokenRefreshRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/skeleton_pkg_data_dto.HTTPResponse-skeleton_internal_api_auth_data_dto_PostAuthTokenRefreshResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/skeleton_pkg_data_dto.ErrorHTTPResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/skeleton_pkg_data_dto.ErrorHTTPResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/skeleton_pkg_data_dto.ErrorHTTPResponse"
                        }
                    }
                }
            }
        },
        "/public/api/health": {
            "get": {
                "description": "Endpoint to check the health of the service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public API / Etc"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/skeleton_pkg_data_dto.HTTPResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/skeleton_pkg_data_dto.ErrorHTTPResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "skeleton_internal_api_auth_data_dto.PostAuthLoginRequestDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "skeleton_internal_api_auth_data_dto.PostAuthLoginResponseDTO": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/skeleton_internal_api_user_data_dto.UserDTO"
                }
            }
        },
        "skeleton_internal_api_auth_data_dto.PostAuthTokenRefreshRequestDTO": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "skeleton_internal_api_auth_data_dto.PostAuthTokenRefreshResponseDTO": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                }
            }
        },
        "skeleton_internal_api_user_data_dto.UserDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "skeleton_pkg_data_dto.ErrorDto": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "skeleton_pkg_data_dto.ErrorHTTPResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/skeleton_pkg_data_dto.ErrorDto"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "skeleton_pkg_data_dto.HTTPResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "skeleton_pkg_data_dto.HTTPResponse-skeleton_internal_api_auth_data_dto_PostAuthLoginResponseDTO": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/skeleton_internal_api_auth_data_dto.PostAuthLoginResponseDTO"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "skeleton_pkg_data_dto.HTTPResponse-skeleton_internal_api_auth_data_dto_PostAuthTokenRefreshResponseDTO": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/skeleton_internal_api_auth_data_dto.PostAuthTokenRefreshResponseDTO"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "skeleton_pkg_data_dto.ValidationError": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "skeleton_pkg_data_dto.ValidationErrorDto": {
            "type": "object",
            "properties": {
                "detail": {
                    "$ref": "#/definitions/skeleton_pkg_data_dto.ValidationError"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "skeleton_pkg_data_dto.ValidationErrorHTTPResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/skeleton_pkg_data_dto.ValidationErrorDto"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Skeleton API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
